### PR TITLE
Update pclzip for compatibility with PHP 7

### PR DESCRIPTION
**Pull request by exside**
### What does it do ?

Updates the pclzip library with a PHP7 compatible version that is a non-official one from Piwik project here https://github.com/piwik/component-decompress/blob/abf7785706fd2b1a8fedbf4a8ec39778756ce596/libs/PclZip/pclzip.lib.php
### Why is it needed ?

Probably to make MODX run properly under PHP7 as the current pclzip lib uses the removed function set_magic_quotes_runtime(), ~~didn't test though =/...will update as soon as I can confirm that it's working properly!~~ edit: no, didn't experience any issues with package management under PHP7 (at least not unpacking archives)
### Related issue(s)/PR(s)

https://github.com/modxcms/revolution/issues/12797

### CODE REVIEW

**Comment by exside** [comment]
While there doesn't seem to be an actual problem (at least not for unzipping) with the current version of the library under PHP 7 I also do not run into any issues unzipping with this updated version...creating packages would be something else to test as it involves CREATING an archive.

**Comment by opengeek** [comment]
@exside How did you test this?

**Comment by exside** [comment]
- Installed new package downloaded from the default extras provider (will unzip the transport zip)
- Unzipped an archive from the file tree (context menu)
- Packing up a transport package should be tested as well though, didn't to that...

**Comment by opengeek** [comment]
I meant, how did you get it to use pclzip? This is only used if manually set in the system settings...

**Pull request closed without merging**
