### PR TITLE
Restrict extracted files to allowed extensions by option

### PR DESCRIPTION
**Pull request by Jako**
Add the changes that are prepared to be introduced in modxcms/revolution#14472 into xPDO.

### CODE REVIEW

**Comment by Jako** [comment]
I will prepare some additional test cases for this.

**Review by Mark-H — APPROVED** [review]
I like this. @opengeek, thoughts?

**Comment by opengeek** [comment]
I like it, but this should not exist as a PR. The changes from xPDO have to be subtree merged into MODX.

**Comment by Jako** [comment]
I have reverted the xPDO changes in https://github.com/modxcms/revolution/pull/14472 to the current state in this repository.

**Pull request merged**
